import { useState } from "react";
import { Link } from "react-router-dom";
import { FileText, Send, RotateCcw, Shield } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";

const Home = () => {
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState({
    reporter_name: "",
    department: "",
    item_name: "",
    quantity: 1,
    description: "",
  });

  const today = new Date().toLocaleDateString("id-ID", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: name === "quantity" ? parseInt(value) || 1 : value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.reporter_name || !formData.department || !formData.item_name) {
      toast({
        title: "Form tidak lengkap",
        description: "Mohon lengkapi semua field yang wajib diisi.",
        variant: "destructive",
      });
      return;
    }

    setIsSubmitting(true);

    try {
      const { error } = await supabase.from("complaints").insert([{
        reporter_name: formData.reporter_name,
        department: formData.department,
        item_name: formData.item_name,
        quantity: formData.quantity,
        description: formData.description || null,
        ticket_number: "", // Will be auto-generated by trigger
      }]);

      if (error) throw error;

      toast({
        title: "Pengaduan berhasil dikirim",
        description: "Laporan Anda telah berhasil disimpan dan akan segera diproses.",
      });

      // Reset form
      setFormData({
        reporter_name: "",
        department: "",
        item_name: "",
        quantity: 1,
        description: "",
      });
    } catch (error) {
      toast({
        title: "Gagal mengirim pengaduan",
        description: "Terjadi kesalahan. Silakan coba lagi.",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleReset = () => {
    setFormData({
      reporter_name: "",
      department: "",
      item_name: "",
      quantity: 1,
      description: "",
    });
  };

  return (
    <div className="min-h-screen bg-secondary">
      {/* Header */}
      <header className="bg-primary shadow-soft">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileText className="h-8 w-8 text-primary-foreground" />
            <div>
              <h1 className="text-xl font-bold text-primary-foreground">SIPebaru</h1>
              <p className="text-sm text-primary-foreground/80">
                Sistem Informasi Pengaduan Barang Rusak
              </p>
            </div>
          </div>
          <Link to="/login">
            <Button variant="secondary" size="sm" className="gap-2">
              <Shield className="h-4 w-4" />
              Admin Login
            </Button>
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8 max-w-2xl">
        <Card className="shadow-soft animate-fade-in">
          <CardHeader className="text-center pb-6">
            <CardTitle className="text-2xl font-bold text-foreground">
              Form Pengaduan Barang Rusak
            </CardTitle>
            <p className="text-muted-foreground mt-2">
              Silakan isi form berikut untuk melaporkan barang rusak
            </p>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              {/* Tanggal Lapor */}
              <div className="space-y-2">
                <Label htmlFor="report_date">Tanggal Lapor</Label>
                <Input
                  id="report_date"
                  value={today}
                  disabled
                  className="bg-muted"
                />
              </div>

              {/* Nama Pelapor */}
              <div className="space-y-2">
                <Label htmlFor="reporter_name">
                  Nama Pelapor <span className="text-destructive">*</span>
                </Label>
                <Input
                  id="reporter_name"
                  name="reporter_name"
                  placeholder="Masukkan nama lengkap"
                  value={formData.reporter_name}
                  onChange={handleInputChange}
                  required
                />
              </div>

              {/* Departemen */}
              <div className="space-y-2">
                <Label htmlFor="department">
                  Departemen <span className="text-destructive">*</span>
                </Label>
                <Input
                  id="department"
                  name="department"
                  placeholder="Masukkan nama departemen"
                  value={formData.department}
                  onChange={handleInputChange}
                  required
                />
              </div>

              {/* Nama Barang */}
              <div className="space-y-2">
                <Label htmlFor="item_name">
                  Nama Barang <span className="text-destructive">*</span>
                </Label>
                <Input
                  id="item_name"
                  name="item_name"
                  placeholder="Masukkan nama barang yang rusak"
                  value={formData.item_name}
                  onChange={handleInputChange}
                  required
                />
              </div>

              {/* Jumlah Unit */}
              <div className="space-y-2">
                <Label htmlFor="quantity">Jumlah Unit</Label>
                <Input
                  id="quantity"
                  name="quantity"
                  type="number"
                  min={1}
                  placeholder="1"
                  value={formData.quantity}
                  onChange={handleInputChange}
                />
              </div>

              {/* Keterangan */}
              <div className="space-y-2">
                <Label htmlFor="description">Keterangan</Label>
                <Textarea
                  id="description"
                  name="description"
                  placeholder="Jelaskan kondisi kerusakan barang..."
                  rows={4}
                  value={formData.description}
                  onChange={handleInputChange}
                />
              </div>

              {/* Buttons */}
              <div className="flex gap-3 pt-4">
                <Button
                  type="submit"
                  className="flex-1 gap-2"
                  disabled={isSubmitting}
                >
                  <Send className="h-4 w-4" />
                  {isSubmitting ? "Mengirim..." : "Kirim"}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleReset}
                  className="gap-2"
                >
                  <RotateCcw className="h-4 w-4" />
                  Reset Form
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </main>

      {/* Footer */}
      <footer className="container mx-auto px-4 py-6 text-center text-muted-foreground text-sm">
        © 2024 SIPebaru - Sistem Informasi Pengaduan Barang Rusak
      </footer>
    </div>
  );
};

export default Home;